version: "3.8"
services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservice-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      - microservice-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8989:8989"
    depends_on:
      - eureka-server
    networks:
      - microservice-net
   
networks:
  microservice-net:
    driver: bridge
